---
- name: Base system setup
  hosts: all
  become: true

  tasks:

    - name: Install vim, firewalld, zstd
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - firewalld
        - zstd

    - name: Set hostname
      ansible.builtin.hostname:
        name: mxrt.eu
        use: redhat

    - name: Set shell for admin to bash
      ansible.builtin.user:
        name: admin
        shell: /usr/bin/bash
