---
- name: Base system setup
  hosts: all
  become: true

  tasks:

    - name: Copy sources.list
      ansible.builtin.template:
        src: etc/apt/sources.list.j2
        dest: /etc/apt/sources.list
        mode: "0644"

    - name: Install vim, firewalld, zstd
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - firewalld
        - zstd

    - name: Set hostname
      ansible.builtin.hostname:
        name: mxrt.de
        use: debian

    - name: Set shell for admin to bash
      ansible.builtin.user:
        name: admin
        shell: /usr/bin/bash
