#!/bin/bash
#adapted from https://github.com/atmoz/sftp/blob/master/files/entrypoint

# Generate unique ssh keys for this container, if needed
if [ ! -f /keys/ssh_host_ed25519_key ]; then
    ssh-keygen -t ed25519 -f /keys/ssh_host_ed25519_key -N ''
fi

if [ ! -f /keys/ssh_host_rsa_key ]; then
    ssh-keygen -t ssh-rsa -b 2048 -f /keys/ssh_host_rsa_key -N ''
fi

# Restrict access from other users
chmod 600 /keys/ssh_host_ed25519_key || true
chmod 600 /keys/ssh_host_rsa_key || true

# -D: do not detach
# -e: write debug logs to stderr
# -d: debug mode, use for testing only
/usr/sbin/sshd -D -e -ddd