---
- name: Setup wireguard
  hosts: all
  become: true
  vars_files:
    private_key.yml   # Run with --ask-vault-pass

  tasks:

    - name: "Install wireguard packages"
      ansible.builtin.dnf:
        name: "wireguard-tools"
        state: present

    - name: "Enable wireguard kernel module"
      community.general.modprobe:
        name: wireguard
        state: present


    - name: Create wireguard config directory
      ansible.builtin.file:
        dest: /etc/wireguard
        state: directory
        mode: 0700

    - name: Copy wireguard config file
      ansible.builtin.template:
        src: etc/wireguard/wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: 0600

    - name: open port 51820
      ansible.posix.firewalld:
        port: 51820/udp
        permanent: true
        state: enabled

    - name: add wg0 to internal zone
      ansible.posix.firewalld:
        zone: internal
        interface: wg0
        state: enabled
        permanent: true

    - name: add 10.0.0.1/24 to as source to internal zone
      ansible.posix.firewalld:
        zone: internal
        source: 10.0.0.1/24
        state: enabled
        permanent: true

    - name: accept internal
      ansible.posix.firewalld:
        zone: internal
        state: present
        permanent: true
        target: ACCEPT
    
    - name: restart firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted

    - name: Start and enable Wireguard service
      ansible.builtin.service:
        name: "wg-quick@wg0"
        state: restarted
        enabled: true
