FROM caddy:2.8.4-builder AS builder

RUN xcaddy build \
    --with github.com/caddyserver/jsonc-adapter

FROM caddy:2.8.4-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

COPY config.jsonc /etc/caddy/config.jsonc

CMD ["caddy", "run", "--config", "/etc/caddy/config.jsonc", "--adapter", "jsonc"]